### ISSUE TITLE
Detail page feedback

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#176]
Branch: https://github.com/CATcher-org/WATcher/tree/Profile-page

- [ ] https://github.com/CATcher-org/WATcher/pull/132#issuecomment-1618025007
- [ ] https://github.com/CATcher-org/WATcher/pull/132#issuecomment-1618139193
- [ ] https://github.com/CATcher-org/WATcher/pull/133#pullrequestreview-1521219991
- [ ] https://github.com/CATcher-org/WATcher/pull/134#issuecomment-1635798583
